### ISSUE TITLE
下载回来模型和data 跑test 的时候报错

### ISSUE THREAD

**Issue by huwei1024** [zhaogaofeng611/TextMatch#5]
Traceback (most recent call last):
  File ".\test.py", line 51, in <module>
    main("d:\\test.csv", "models/best.pth.tar")
  File ".\test.py", line 43, in main
    model.load_state_dict(checkpoint["model"])
  File "C:\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 1044, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for BertModelTest:
        Missing key(s) in state_dict: "bert.bert.embeddings.position_ids".

如何解决？

**Comment by zskyliang** [comment]
model.load_state_dict(checkpoint['model'],strict=False)

**Comment by ruthy-wei** [comment]
你解决了嘛？跟你遇到同意的问题..

**Comment by monkdou0** [comment]
same question

**Comment by yh7109** [comment]
加一个False就好了
model.load_state_dict(checkpoint["model"], False)
